function obj = generateFile(settings,obj)
    clc
    searchFolder = [obj.mainFolder '\identification\SearchGUI-3.3.20'];
    cd(searchFolder);
    jar_struct = dir('*.jar'); 
    searchGUI_jar = jar_struct.name;
    fasta_struct = dir('*.fasta');
    fastaFile = fasta_struct.name;
    system(['cd ' searchFolder]);
    system(['java -cp ' searchGUI_jar ' eu.isas.searchgui.cmd.IdentificationParametersCLI',...
        ' -out ' settings.parameterFileName,...
        ' -db ' fastaFile,...
        ' -prec_tol ' settings.general.MS1Tolerance,...
        ' -frag_tol ' settings.general.MS2Tolerance,...
        ' -mc ' settings.general.miscleavages,...
        ' -min_charge ' settings.general.minimumCharge,...
        ' -max_charge ' settings.general.maximumCharge,...
        ' -annotation_level ' settings.general.annotationLevel,...
        ' -import_peptide_length_min ' settings.general.minPeptideLength,...
        ' -import_peptide_length_max ' settings.general.maxPeptideLength,...
        ' -useGeneMapping ' settings.general.geneAnnotation,...
        ' -db_pi ' fastaFile,...
        ' -xtandem_dynamic_range ' settings.xtandem.dynamicRange,...
        ' -xtandem_min_frag_mz ' settings.xtandem.minFragmentMZ,...
        ' -xtandem_quick_acetyl ' settings.xtandem.acetyl,...
        ' -xtandem_quick_pyro ' settings.xtandem.pyro,...
        ' -xtandem_refine ' settings.xtandem.refinement,...
        ' -xtandem_min_prec_mass ' settings.xtandem.minPrecMZ,...
        ' -msgf_min_pep_length ' settings.general.minPeptideLength,...
        ' -msgf_max_pep_length ' settings.general.maxPeptideLength,...
        ' -omssa_min_pep_length ' settings.general.minPeptideLength,...
        ' -omssa_max_pep_length ' settings.general.maxPeptideLength]);
    cd(obj.mainFolder);
end
